### PR TITLE
Adding Knative Eventing CR

### PR DESCRIPTION
**Pull request by cardil**
As title says. Adding Eventing CR to the cluster. I think its good idea to have that as we are incorporating eventing into the serverless operator for 1.7

### CODE REVIEW

**Comment by bbrowning** [comment]
Given that this is for 1.7, should I hold off on doing anything with it until 1.7 is released?

**Comment by cardil** [comment]
Now 1.7 is live this can be merged safely, right?

**Comment by bbrowning** [comment]
So...I might have forgotten about this PR when updating the cluster to 1.7.0. I went through a whole process to remove the old community eventing and get the new eventing via openshift serverless installed. That means that the actual changes to install eventing via openshift serverless from this PR are already in.

This PR does clean up the repo layout a bit by nesting things under a knative/ folder, which I'm not philosophically opposed to. However, I'd worry about what Argo would do with a rename like that and if it would accidentally delete and reinstall serving and eventing from the cluster by moving the folders here.

**Comment by cardil** [comment]
Okay. I'm okay with dropping this.

**Pull request closed without merging**
